// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: decks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, source_language, target_language)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, source_language, target_language, created_at
`

type CreateDeckParams struct {
	UserID         uuid.UUID
	Name           string
	SourceLanguage string
	TargetLanguage string
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.SourceLanguage,
		arg.TargetLanguage,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SourceLanguage,
		&i.TargetLanguage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, source_language, target_language, created_at FROM decks WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SourceLanguage,
		&i.TargetLanguage,
		&i.CreatedAt,
	)
	return i, err
}

const getDecksByUserID = `-- name: GetDecksByUserID :many
SELECT id, user_id, name, source_language, target_language, created_at FROM decks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDecksByUserID(ctx context.Context, userID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, getDecksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SourceLanguage,
			&i.TargetLanguage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
