// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Deck struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	SourceLanguage string
	TargetLanguage string
	CreatedAt      pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	ClerkID   string
	Email     string
	CreatedAt pgtype.Timestamp
}
